name: "DEV deploy"

on: 
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::063630845645:role/github-actions-pipeline-infra"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "cidade-refugio-statefiles"
      aws-lock-dynamodb-table: "cidade-refugio-terraform-lock"
